name: Deploy to Payara Cloud

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      # non-standard Payara Cloud Endpoint, not really thing to document at this point
      PCL_ENDPOINT: https://manage.dev02-head.payara.cloud
      PCL_CLIENT_ID: "OPWL6h4SUxPHa1rMZ9flPStKkxnMQj8H"
      # token obtained from `pcl login --print-token`
      PCL_AUTH_TOKEN: ${{ secrets.PCL_AUTH_TOKEN }}
      PCL_VERSION: 1.0.1
      PCL: pcl-1.0.1/bin/pcl

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          # we only use direct match of pom.xml. So a version change will surely drop the cache
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}

      - name: Build with Maven
        run: mvn -B verify

      # upload-artifact / download-artifact actions can be used to sepearate these into separate jobs
      - name: Download PCL
        # This should download PCL from official download location rather than our internal Maven repo
        # unzip cannot do pipes. jar can, but it ignores file permissions
        run: |
          curl https://nexus.payara.fish/repository/payara-artifacts/fish/payara/cloud/pcl/$PCL_VERSION/pcl-$PCL_VERSION.zip -o pcl.zip
          unzip pcl.zip
          rm pcl.zip

      - name: Deploy application
        run: |
          $PCL upload -n start-dev target/ci-demo.war --deploy

